name: npm_publish

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  version-checking:
    name: "Version Checking"
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged && github.head_ref == 'dev' }}
    outputs:
      previousVersion: ${{ steps.version_updated.outputs.previous-version }}
      currentVersion: ${{ steps.version_updated.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: johnnybenson/package-json-versioned-action@v1.0.8
        id: version_updated
        with:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Show Previous Version
        run: echo "previousVersion = ${{ steps.version_updated.outputs.previous-version }}"
      - name: Show Current Version
        run: echo "currentVersion = ${{ steps.version_updated.outputs.version }}"

  publish-npm:
    name: "Publish"
    runs-on: ubuntu-latest
    needs: version-checking
    if: ${{ needs.version-checking.outputs.previousVersion < needs.version-checking.outputs.currentVersion }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  canceled:
    name: "Cancel"
    runs-on: ubuntu-latest
    needs: version-checking
    if: ${{ needs.version-checking.outputs.previousVersion >= needs.version-checking.outputs.currentVersion }}
    steps:
      - uses: vishnudxb/cancel-workflow@v1.2
        with:
          repo: huibizhang/vuepress-plugin-simple-blog
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}
